version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    container_name: ratekeeper-db
    restart: always
    environment:
      MYSQL_DATABASE: ratekeeper
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306